LOAD DATA LOCAL INFILE 'user.csv' INTO TABLE user FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'item.csv' INTO TABLE item FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'item_category.csv' INTO TABLE item_category FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'item_bid.csv' INTO TABLE item_bid FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bidder.csv' INTO TABLE bidder FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'seller.csv' INTO TABLE seller FIELDS TERMINATED BY '|*|';